In [5]:
arr1=np.array([1,2,3,4,5,34,23,3,4])


In [6]:
arr1.shape

(9,)

In [7]:
arr1.ndim

1

In [20]:
arr2=np.array([[1,2,3,4],[5,6,7,8],[2,3,4,5],[4,2,7,9]])
arr2.shape
arr2.size
arr2.ndim
arr2.dtype
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [4, 2, 7, 9]])

In [22]:
arr2[-1:]

array([[4, 2, 7, 9]])

In [23]:
arr2[1:3,1:3]

array([[6, 7],
       [3, 4]])

In [39]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9],[2,3,4],[5,6,7],[2,3,4],[4,9,6]])
arr4


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4],
       [5, 6, 7],
       [2, 3, 4],
       [4, 9, 6]])

In [44]:
arr4[0::6,0::2]=-1
arr4

array([[-1,  2, -1],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 2,  3,  4],
       [-1,  9, -1]])

In [46]:
arr4[[0,1,5],[1,1,1]]=[51,52,53]
arr4

array([[-1, 51, -1],
       [ 4, 52,  6],
       [ 7,  8,  9],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 2, 53,  4],
       [-1,  9, -1]])

In [65]:
arr4[[0,1,4]]=255
arr4

array([[255, 255, 255],
       [255, 255, 255],
       [  7,   8,   9],
       [  2,   3,   4],
       [255, 255, 255],
       [  2,  53,   4],
       [ -1,   9,  68]])

In [68]:
arr4[arr4%2==0]


array([ 8,  2,  4,  2,  4, 68])

In [85]:
import numpy as np  
arr = np.array([[12, 45, 7, 19, 34, 28, 90, 55, 63]])
arr
arr[arr>30]
arr[arr%2!=0]
arr[arr%5==0]=-1
arr
arr = np.array([12, 45, 7, 19, 34, 28, 90, 55, 63])
sum(arr<50)

np.int64(6)

In [82]:
arr = np.array([[10, 25, 40], [55, 18, 72], [91, 30, 64]])
arr[arr>50]
arr[arr%2==0]=0
arr
arr = np.array([[10, 25, 40], [55, 18, 72], [91, 30, 64]])
sum(arr[arr%5==0])
arr = np.array([[10, 25, 40], [55, 18, 72], [91, 30, 64]])
len(arr[(arr>20) & (arr<70)])

5

In [71]:
arr = np.array([[12, 34, 56],[78, 90, 23],[45, 67, 89]])
arr[0:3:2]
arr = np.array([[12, 34, 56],[78, 90, 23],[45, 67, 89]])
arr[:,1]
arr = np.array([[12, 34, 56],[78, 90, 23],[45, 67, 89]])
arr[[0,1,2],[0,1,1]]
arr = np.array([[12, 34, 56],[78, 90, 23],[45, 67, 89]])
arr[[2,1,0],:]

array([[45, 67, 89],
       [78, 90, 23],
       [12, 34, 56]])

In [87]:
arr = np.array([[5, 15, 25],[35, 45, 55],[65, 75, 85]])
arr[(arr%5==0) & (arr>30)]
arr = np.array([[5, 15, 25],[35, 45, 55],[65, 75, 85]])
arr[arr<50]=-1
arr
arr = np.array([[5, 15, 25],[35, 45, 55],[65, 75, 85]])
arr[:,2:]=100
arr
arr = np.array([[5, 15, 25],[35, 45, 55],[65, 75, 85]])
arr[arr>60]*= 2
arr

array([[  5,  15,  25],
       [ 35,  45,  55],
       [130, 150, 170]])

In [102]:
arr = np.array([[5, 15, 25],[35, 45, 55],[65, 75, 85]])
arr[:,2:]=100
arr


array([[  5,  15, 100],
       [ 35,  45, 100],
       [ 65,  75, 100]])

In [103]:
np.sum(arr)

np.int64(540)

In [105]:
np.sum(arr,axis=1)

array([120, 180, 240])

In [106]:
np.min(arr)

np.int64(5)

In [111]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [112]:
np.full((5,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [124]:
# np.full_like(a,1)
b=np.arange(100,0,-1)
b
np.reshape(arr,(9,))

array([  5,  15, 100,  35,  45, 100,  65,  75, 100])

In [140]:
np.random.randint(1,10,(10,5))

array([[4, 6, 6, 7, 4],
       [9, 5, 7, 7, 6],
       [2, 4, 5, 9, 6],
       [9, 3, 3, 9, 5],
       [5, 1, 3, 7, 8],
       [6, 9, 4, 1, 7],
       [6, 3, 8, 2, 4],
       [4, 1, 3, 6, 2],
       [1, 6, 4, 3, 5],
       [5, 1, 2, 6, 9]], dtype=int32)

In [88]:
arr[[0,2]]=arr[[2,0]]
arr

array([[130, 150, 170],
       [ 35,  45,  55],
       [  5,  15,  25]])

In [89]:
arr

array([[130, 150, 170],
       [ 35,  45,  55],
       [  5,  15,  25]])

In [95]:
# greater than 50 count
arr>50

array([[ True,  True,  True],
       [False, False,  True],
       [False, False, False]])

In [97]:
arr[(arr>20)&(arr<70)]

array([35, 45, 55, 25])

In [96]:
sum(arr>50)


array([1, 1, 2])

In [98]:
arr = np.array([[5, 15, 25],[35, 45, 55],[65, 75, 85]])
arr[arr>60]*= 2
arr

array([[  5,  15,  25],
       [ 35,  45,  55],
       [130, 150, 170]])

In [63]:
arr6=np.random.randint(1,100,(7,3))
arr6

array([[90,  3, 62],
       [48, 78, 53],
       [77,  6, 65],
       [41, 57, 21],
       [80, 42, 46],
       [62, 13,  4],
       [45, 52, 18]], dtype=int32)

In [31]:
arr3[:,::2]

array([[1, 3],
       [4, 6],
       [7, 9],
       [2, 4],
       [5, 7],
       [2, 4],
       [4, 6]])

In [15]:
arr1=np.array([1,2,3,4,5])
arr2=arr1+1
arr2
arr1[2:4]=[20,30]
arr1

array([ 1,  2, 20, 30,  5])

In [4]:
import numpy as np

In [5]:
import numpy

In [3]:
a=10
b=12
a+b

22

In [1]:
print("hello")

hello
